[project]
name = "mytools"
version = "0.1.0"
description = "Moje przydatne narzędzia w Pythonie"
authors = [
  { name="Shurarek", email="shuvarek@email.com" }
]
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

